### ISSUE TITLE
add partial message response configuration to the deployment

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#168]
Sending a partial message response to an observer should become configurable. The default would be that it is *not* enabled but could be enabled in the deployment configuration screen.

**Comment by blynchNDI** [comment]
Feature is working

**Comment by blynchNDI** [comment]
@SarahCooperNDI - Just want to verify that this is expected behavior: When partial message response is turned on, the system accepts a partial answer as valid but tells you that a part is missing. When partial message response is turned off, it simply accepts a partial answer as valid without any additional message.

**Comment by SarahCooperNDI** [comment]
@blynchNDI Correct -- that is the behavior we are expecting.  Thanks for testing!!
