### ISSUE TITLE
ability to choose whether to track conflicts on checklist forms

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#175]
A new feature should be added to the checklist set-up allowing the user to indicate whether observers in a given location are expected to send the same information (this is the current Apollo set-up -- if two observers tied to the same location send conflicting information it is flagged as a conflict in the database) or if observers in a given location could send different information (as is currently the case with critical incidents - critical incidents from one location can include different information).

Aha! Link: https://nditech.aha.io/features/APOLLO-188

**Comment by dodumosu** [comment]
It seems this was covered by #76, or was it not?

**Comment by blynchNDI** [comment]
@SarahCooperNDI I have Test Event set up with a two participant model. The option is available on the form builder to enable tracking conflicts, which means that if conflicting data is sent in, the data is flagged and does not appear on the dashboard or result summary page. This seems to work as desired. However when track conflict is not enabled, data isn't flagged as conflicting, but it still combines the two reports into one location column (taking the most recent submission from the two observers for a given field), and creates one entry in the results summary page. It sounds like the feature we want here would be to add another option so that not only are conflicts not tracked, but the results are not combined either (e.g. 200 participants grouped in pairs would create 200 data points rather than 100). Is this correct then that we need an additional feature here?

**Comment by blynchNDI** [comment]
Or actually in the case where you want multiple reporters at the same location to send in different data points, would you just create separate location codes for them?

**Comment by SarahCooperNDI** [comment]
@blynchNDI @takinbo @dodumosu I just spoke with Richard (we are finally in the same location!) and - if at all possible - we would want to want to do as Ben suggests and adapt the Dashboard and Data Summary pages so that when there are multiple observers and no conflicts tracked their results are not combined.  So, for example here is what would happen for an observation effort with 500 observers deployed in pairs in both the "conflicts tracked" "conflicts not tracked" scenarios:

**Conflicts Tracked**
-Dashboard shows 250 total reports
-Master Data and Observer Data exports are possible - Master Data shows the data for the first observer in the pair provided the data is not in conflict -- data in conflict is missing from the export
-Data Summary shows responses as a percentage of 250

**Conflicts Not Tracked**
-Dashboard shows 500 total reports
-Observer Data and Master Data exports are the same (so Master Data is not necessary)
-Data Summary shows responses as a percentage of 500

Tim, I know you said this would be a much heavier lift, so let's discuss tomorrow (June 12) how that might affect the updated Apollo 3.0 timeline that you sent to us on Monday.

**Comment by blynchNDI** [comment]
All requirements described in Sarah's comment above appear to be met
