### ISSUE TITLE
add a new category for tracking participants that cannot be reached or "no signal"

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#188]
Create a grey category for observers with no signal that will appear on the pie and bar charts. The category will also appear on the checklists (use an intuitive icon). Initial plan was to mark the participant as unavailable but that would affect checklists in other events that are linked to the participant so the new plan is to mark the checklist itself. If the participant is meant to send a report on more than one checklist, the data clerk will be required to mark each checklist as _no signal_.

Aha! Link: https://nditech.aha.io/features/APOLLO-175

**Comment by blynchNDI** [comment]
There is now an offline checkbox on the checklist that can be selected. Checking it causes the symbol on the checklist page to change. The filter by offline/online status also works

**Comment by SarahCooperNDI** [comment]
This toggle should be changed from "online" and "offline" to "signal" and "no signal."  Because SMS is still the primary means of sending information (not smartphone or laptop) we are not interested to know whether the observer has internet access.  We want to be able to indicate if a user has no cellphone reception (no signal). @takinbo @dodumosu @blynchNDI

**Comment by SarahCooperNDI** [comment]
At present the toggles on the checklist landing page do not work (only when you enter into a participant record). Could the toggles on the checklist page also be made to work? The below screenshot shows which toggles I am referring to.

![Apollo Toggles to Fix](https://user-images.githubusercontent.com/48285413/57384206-23aeff80-717e-11e9-9f8c-bc0b159b16a7.png)

**Comment by SarahCooperNDI** [comment]
When editing a checklist record, the "Offline?" category should be switched "Signal".  Could there then be a drop-down menu (just as there is for quarantine status below) with options "Signal" and "No Signal" with "Signal" selected as the default status rather than a checkbox?

![Offline Status - No Signal and Switch to Drop Down Menu](https://user-images.githubusercontent.com/48285413/57657502-830b7600-75a9-11e9-84ad-3b3e091d33d8.png)

**Comment by blynchNDI** [comment]
Looks good, the only additional request is to change the checkbox to a dropdown menu with "Signal" and "No Signal" as the only two dropdown choices (unless @SarahCooperNDI you have a preference to name the dropdown choices something different)

**Comment by SarahCooperNDI** [comment]
@blynchNDI "Signal" and "No Signal" will be excellent - thanks!

**Comment by takinbo** [comment]
![screenshot-1559737130](https://user-images.githubusercontent.com/41004/58955678-1e989c80-878c-11e9-87a9-762b06e65e01.png)

@blynchNDI @SarahCooperNDI what are your thoughts on this design within the screen for editing a checklist?

**Comment by SarahCooperNDI** [comment]
> ![screenshot-1559737130](https://user-images.githubusercontent.com/41004/58955678-1e989c80-878c-11e9-87a9-762b06e65e01.png)
> 
> @blynchNDI @SarahCooperNDI what are your thoughts on this design within the screen for editing a checklist?

I like it but when we last met on this Richard proposed a drop down menu so that it is consistent with the menu for quarantine status just below.  The fewer different types of inputs we have to teach the data clerks the better. Could we create a drop-down menu like the one for quarantine status but with options Signal and No Signal instead? Signal should be selected as the default status.

**Comment by takinbo** [comment]
That's fine. We'll make the change.

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI It seems we have now lost the ability to quarantine data in the checklist? We have a different signal toggle but no quarantine drop-down menu.

![Signal Toggle - No Quarantine Drop-down](https://user-images.githubusercontent.com/48285413/59953707-51f74e80-944f-11e9-9296-5ca85b6d02e5.png)

**Comment by blynchNDI** [comment]
'No signal' feature is implemented and working
