### ISSUE TITLE
if text message group names are longer than 7 characters, truncate it

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#190]
The truncated name should also display a tooltip with the full name

Aha! Link: https://nditech.aha.io/features/APOLLO-173

**Comment by blynchNDI** [comment]
Not sure what this issue refers to, maybe @SarahCooperNDI or @sarahmoulton can enlighten?

**Comment by SarahCooperNDI** [comment]
If we name a section on a checklist something that is more than seven characters long we want it to truncate on the checklist page to just the first seven characters (this is about trying to get more space on the screen). So for example if we named a section Voting and Accreditation all we would want to see on the checklist --> form page would be "Voting " with the option to see the full name (Voting and Accreditation) when you hover over it with the mouse.  These are the names we are referring to:

![Seven Characters Truncation](https://user-images.githubusercontent.com/48285413/57704099-45513080-762f-11e9-93a3-9e24b00da4fb.png)

@blynchNDI

**Comment by blynchNDI** [comment]
![Screenshot from 2019-05-15 09-31-59](https://user-images.githubusercontent.com/31080607/57779581-544de680-76f4-11e9-92a7-2866bd3fd844.png)

Thanks @SarahCooperNDI - it appears this is implemented except that there is a slightly higher number of characters allowed before it abbreviates, and it abbreviates to the first four letters. Is this close enough to your specs?

**Comment by blynchNDI** [comment]
Per conversations with Sarah Cooper, it would be preferable to have seven characters display followed by the three periods, rather than only four characters and the periods ("Section..." instead of "Sect...")

**Comment by SarahCooperNDI** [comment]
@blynchNDI My apologies! I was not particularly clear.  What we would want actually is to eliminate the ellipses -- the point of truncating is to save space on the interface and having ... uses up space to no real functional end.  So instead of say "Accreditation" could we have it truncate to the first 7 characters, so "Accredi", and then when you hover "Accreditation" would show? Hopefully our clerks are smart enough to figure out that things are being truncated if we explain the logic of the system to them even without seeing the ...  Does that make sense? @takinbo @dodumosu

**Comment by blynchNDI** [comment]
Ah ok thanks for clarifying Sarah!

**Comment by takinbo** [comment]
Makes sense. Would update the logic for that. The only way to know that a title has been truncated is to probably have the ellipsis left in the title so I'm in favour of leaving it there.

**Comment by SarahCooperNDI** [comment]
> Makes sense. Would update the logic for that. The only way to know that a title has been truncated is to probably have the ellipsis left in the title so I'm in favour of leaving it there.

I think that would be true if there were no outside context for the titles, but the data clerks all have copies of the checklists and (should) understand that the message names correspond to the checklist sections. The interface won't be quite as visually nice without the ellipses (I agree) but we have had a real problem with running out of space on the checklist page and clerks having to zoom their screens out impractically far so that they can see all message statuses without scrolling. So I would rather we go with function over form in this case. Let's please drop the ellipses. :-)
