### ISSUE TITLE
come up with a method to flag checklists that have a comment(s) without having to scroll all the way to the bottom of the checklist

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#197]
If possible, also show an indicator on the lists page so the user knows when a comment(s) has been added to that checklist.

Aha! Link: https://nditech.aha.io/features/APOLLO-166

**Comment by blynchNDI** [comment]
![Screenshot from 2019-05-01 16-56-28](https://user-images.githubusercontent.com/31080607/57042214-1485fa00-6c32-11e9-910f-00b3cd3fa532.png)

A question bubble now appears next on the checklist page next to an entry that has a comment. Does this meet your criteria for this feature @SarahCooperNDI ?

**Comment by blynchNDI** [comment]
@SarahCooperNDI - I think we touched on this on friday - was the comment symbol next to a checklist entry sufficient, or did you want some sort of indicator on the top of the edit checklist page as well?

**Comment by blynchNDI** [comment]
Per conversations with Sarah Cooper, the comment symbol on the checklist page is good, but it would also be good to have something on the top of the edit checklist that flags that there is a comment at the bottom, so that the data clerk remembers to scroll down

**Comment by blynchNDI** [comment]
Comment icon appears on both the checklist page and the edit checklist page. @SarahCooperNDI you can provide feedback on if this is good, or if it should be made more noticeable in anyway (bolded? outline around it? blinking lights?)

![Screenshot from 2019-07-11 05-18-01](https://user-images.githubusercontent.com/31080607/61038645-5ef6c600-a39b-11e9-800f-767d1851a00c.png)

**Comment by blynchNDI** [comment]
Discussed with Sarah C, and is good as implemented

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI I spoke with Richard and we both like the comment icon on the individual checklist pages but we would like to drop it from the checklist dashboard since we already frequently run into problems with not having enough space to show all of the expected SMS on that dashboard without scrolling.  Can we drop the column highlighted in red below?

![Apollo Comment Column](https://user-images.githubusercontent.com/48285413/61543417-6c522700-aa11-11e9-898e-f2320847e4d8.png)

**Comment by blynchNDI** [comment]
Column has been removed
