### ISSUE TITLE
add support for processing some numerical questions as a categorical data type

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#200]
data summaries for those questions would not be processed as simple numeric data showing the mean but rather showing a histogram of the values of the question.

for aggregate data export of categorical data type questions, a column should be created for each possible value of the question.

Aha! Link: https://nditech.aha.io/features/APOLLO-163

**Comment by SarahCooperNDI** [comment]
For numeric data - as discussed on the this week's call - the analysis would be broken out into three types on the form builder.

1) Categorical (with histogram) -- for this data type the data summary would provide a histogram and  count of all reported values for the data (e.g. 10 respondents reported 1, 5 respondents reported 2, 16 respondents reported 3, 12 respondents reported 4, 1 respondent reported 7)
2) Categorical (with expected value) -- the data summary would provide a count of how many respondents reported a value less than the expected value, how many respondents reported a value equal to the expected value and how many respondents reported a value greater than the expected value
3) Continuous -- Operates the same way as numerical data under Apollo 2.0. The data summary would provide the mean value of the data.

**Comment by blynchNDI** [comment]
You can now choose between 3 different results displays as described, and all seem to be working.

**Comment by blynchNDI** [comment]
Reopening this per @RLK-NDI 's request - apparently I closed this prematurely, as Richard pointed out that option 1 as mentioned by Sarah is not currently an analysis option. The request from Richard is to have a histogram option, where rather than having a target value like categorical, the histogram analysis option creates a new column for each response sent in, along with a count number of how many of that response value have been sent in (as of now, there is no request to pre-specify what the expected values are, but rather to just display every new value as a header as it is sent in). Richard mentioned that if this would create formatting issues going horizontally, this analysis section could possibly be turned so it went horizontally instead, and each row is a different response option. I can't remember if we had discussions around the feasibility of this on a call, but Richard is quite insistent on this feature as described being very important for him. I apologize as I know time is limited, but let me know @takinbo and @dodumosu what you are able to do here.

**Comment by takinbo** [comment]
Selecting the "Categorical" analysis and not setting an _Expected Value_ will yield a pure histogram. #519 was merged to highlight the fact that the _Expected Value_ is optional.
