### ISSUE TITLE
in aggregated exports display the name of the level aggregated

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#206]
Aha! Link: https://nditech.aha.io/features/APOLLO-157

**Comment by blynchNDI** [comment]
@takinbo / @dodumosu - the aggregated export on the qa site currently appears to be blank apart from column headers - not sure if you can verify whether this is replicated on your end? I'm also still not entirely looped in on the intent behind the aggregated export, so it might be good to discuss this briefly on Wed before I review the issues pertaining to it. Also let me know if there are aspects of it that you need me to get feedback from Chris on.

**Comment by dodumosu** [comment]
@blynchNDI taken a look and it indeed is blank apart from the headers, which was strange because I was unable to replicate locally. i then took an export of the locations in the system, and found that there isn't any text in the name columns, after which i did some digging around and found that the deployment language was set to Arabic and the additional languages were also set to Arabic, which explained why there were two name columns for Arabic
[test-event-locations-2019-08-13-103658.csv.zip](https://github.com/nditech/apollo/files/3496595/test-event-locations-2019-08-13-103658.csv.zip)

despite setting the language, the issue wasn't resolved. i'm going to go out on a limb and ask if i can get temporary back end access to find out what's going on

i'm going to go out on a limb and ask for backend

**Comment by dodumosu** [comment]
[sample aggregated export](https://github.com/nditech/apollo/files/3506260/test-event-test-checklist-2019-08-15-155059-aggregated.csv.zip)

was unable to reproduce even with exports from the QA site. above is the aggregated export from the event i set up using the export artefacts from the QA site. i recommend building a new event, location set, participant set and testing this again.

**Comment by blynchNDI** [comment]
Export bug moved to a new ticket. Names of levels for aggregated export are displayed
