### ISSUE TITLE
when editing checklists put the label "Observer" in the space above where the participant name is displayed

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#207]
Also change the label from _OBS n_ to _Observer n_ and _PS_ to _Location_

Aha! Link: https://nditech.aha.io/features/APOLLO-156

**Comment by blynchNDI** [comment]
OBS and PS were successfully changed, but it doesn't appear to say "Observer" in the space above where the participant name is displayed

**Comment by blynchNDI** [comment]
@takinbo One more minor fix here - it now says "Observer" at the top, but next to it also has ''1" right after it for every observer. Can this 1 be easily removed?

**Comment by takinbo** [comment]
It can. The reason we don't remove it is to cater for situations where there are more than one observer at the location.

**Comment by blynchNDI** [comment]
Ah ok, we should leave as is then.

**Comment by SarahCooperNDI** [comment]
Looks like thi

**Comment by SarahCooperNDI** [comment]
Looks like this issue from the SoW was not properly pasted into GitHub -- sorry about that!  The SoW reads 'Entitle the currently blank cell above participant as Observer and then rather than 1 the first entry should read OBSERVER 1.'  Please see below a screenshot with what we want in red text.

![Issue 207 Clarification](https://user-images.githubusercontent.com/48285413/57706239-5ac85980-7633-11e9-84ae-b73b59dbe9cf.png)

**Comment by blynchNDI** [comment]
Ah good catch Sarah. @takinbo note Sarah's desired specification in the comment above ^

**Comment by blynchNDI** [comment]
Display now matches Sarah's screenshot
