### ISSUE TITLE
display a list of critical incidents that were sent by an observer in a location on the checklist edit page

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#211]
the structure of the list will display:

1. A unique id with a link to the actual critical incident report
2. Critical incident report type
3. Incident code
4. Status
5. Comment or Message

Aha! Link: https://nditech.aha.io/features/APOLLO-152

**Comment by blynchNDI** [comment]
Looks good. The only issue is that I believe critical incidents forms will sometimes have multiple parts/questions, and the display here treats each question on the incident form as a separate submission, and list the letter of that question rather than a response of any sort. Not sure if @SarahCooperNDI can clarify what is wanted here. Other than that column though, it seems fine.

![Screenshot from 2019-07-17 15-43-11](https://user-images.githubusercontent.com/31080607/61406317-9a1c5c00-a8a9-11e9-8532-a059677280d1.png)

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI We love this new tab feature to show critical incidents, messages and the change log, but Ben is correct that the critical incidents are not behaving the way we would expect them to.  Right now this seems to be logging each question on the critical incident form as a separate incident.

We would want to show:

**ID** : the observer ID -- this is fine)
**Incident ID** : We would like to assign a unique identifier to each critical incident so that we can follow up more easily on particular incidents in the data center. Could we, say, generate a 5 letter code for each critical incident (using letters instead of numbers so that there is no risk of accidentally generating a code that will also be an observer ID).  This Incident ID should be hot so that when it is clicked on it takes you into the checklist page for the incident in question.
The section currently called Type should be renamed **Form Code** and should display the Form Code rather than the name of the form
The section currently called Code should be renamed **Type** and should show the numeric and text response to the first question on the Critical Incident Form (which is always Incident Type). For example we might show here 1 - Ballot Box Stuffing.
**Status** : this section is fine
The **Description** section can be dropped for the sake of space and since we often now set up incident forms so that each question can be accompanied by a description and we only want to show the response to the first Incident Type question in this log.
The **Date** and **Time** sections are fine

Let me know if there are any further questions about this!

**Comment by SarahCooperNDI** [comment]
We will also want to add the Incident ID to the Critical Incident dashboard (see below)

![Insert Incident ID](https://user-images.githubusercontent.com/48285413/61547053-9bb86200-aa18-11e9-90ed-7a4b467bf045.png)

**Comment by takinbo** [comment]
Recommendation: we replace `ID` with the incident id rather than the participant id and then we create another column to display the `Participant ID`?

**Comment by takinbo** [comment]
![screenshot-1564515752](https://user-images.githubusercontent.com/41004/62159988-7d990e80-b302-11e9-9cfb-6cf9f8da05c0.png)
Went with a different approach for the display. Resolved in #448

**Comment by blynchNDI** [comment]
The new format and columns as seen below looks good. The only further requests I would have is with how data is displayed, which are hopefully easy lifts:

1. In the 'Form' column, replacing the letter code with the name of the form (as it would be displayed on the dropdown menu at the top for example). Perhaps though lengthening this would be problematic formatting-wise.
2. The column header 'Type' can now probably be changed to something more fitting such as 'Response' or something of that nature
3. Under the column 'Type' column, it would be ideal for the fully written out answer to be displayed rather than just a number (e.g. for Yes/No questions, display 'Yes' or 'No' rather 1 or 2. Same for writing out the choice selected for a single choice or multiple choice question)

![Screenshot from 2019-08-10 19-00-57](https://user-images.githubusercontent.com/31080607/62827648-3bdd5300-bba1-11e9-8730-7b1fb5688a53.png)

**Comment by takinbo** [comment]
As concerning 1 and 2, please refer to [this response](https://github.com/nditech/apollo/issues/211#issuecomment-513272063) from @SarahCooperNDI 

As concerning 3, historically, the elections team has preferred that numbers (rather than response labels) are displayed so as not to confuse both data clerks and observers about the response they intended to send: "Did you intend to send 1 rather than 2?". As a result, this issue won't be fixed.

**Comment by blynchNDI** [comment]
Ah good catch - should have read the comment history. Sounds like all three of those are then not desirable for the elections team. Will reopen if for some reason 3 is preferred by them, but that seems unlikely. Issue is resolved.

**Comment by blynchNDI** [comment]
Reopening this per Richard's requests as to how critical incidents should be displayed on the edit checklist page. I believe the requested changes were as follows:
1. For each critical incident, only display one line per critical incident per line (e.g. if the observer has sent in 5 critical incidents, there should be 5 lines)
2. The column labeled Type for each incident should just display the answer to the first question for that critical incident (but not the question). Ideally, it would be the number corresponding to the answer as well as the answer itself (e.g. `3 - Ballot Box Tampering` or `5 - Voter Intimidation`
3. Change the column label from 'Type' to 'Incident Type'

All other fields/columns should remain the same (the confusion around the form code column was due to an error in how I had labeled it)

**Comment by blynchNDI** [comment]
@takinbo @dodumosu - just caught that this was reopened but not moved out of done. The same three requirements are still wanted - basically one line per critical incident sent in, and the type column displaying the number sent in along with the answer that that number corresponds to

**Comment by takinbo** [comment]
Only change that had to be made was to change the column title from `Type` to `Incident Type`. As concerning the other issues, they are already implemented. Normally if the critical incident form is adequately designed, it would not have multiple reports and would have only one question. In the example that was used, it had multiple and if the observer answered all, they would appear as different critical incident reports.

**Comment by blynchNDI** [comment]
Will double-check with @RLK-NDI , but this looks good:

![Screenshot from 2019-09-05 16-51-09](https://user-images.githubusercontent.com/31080607/64379658-6209dd80-cffd-11e9-863a-88a0141e2f03.png)

**Comment by blynchNDI** [comment]
Haven't been able to meet with @RLK-NDI , but closing as this seems to meet all requirements
