### ISSUE TITLE
remove "rejected" as an option for verifying checklists after quality assurance condition has been verified.

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#213]
quarantine already handles this so it's redundant to add it to quality assurance

Aha! Link: https://nditech.aha.io/features/APOLLO-150

**Comment by takinbo** [comment]
"Verification" as a feature has been removed in favour of the use of quarantine.

**Comment by SarahCooperNDI** [comment]
Although this issue was closed, it doesn't appear to have been integrated into the latest build.  @takinbo  @dodumosu @blynchNDI  Please see screenshot below which still includes REJECTED criterion.

![Rejected Appears in QA](https://user-images.githubusercontent.com/48285413/58594010-80ac4b80-823a-11e9-8804-3cc712d6c611.png)

**Comment by SarahCooperNDI** [comment]
Looks good to me!  @blynchNDI We can close this out
