### ISSUE TITLE
expand concept of message log to include submissions via a the range of methods accepted by input abstraction layer

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#231]
Aha! Link: https://nditech.aha.io/features/APOLLO-132

**Comment by blynchNDI** [comment]
Pending further discussion on how best to display this

**Comment by blynchNDI** [comment]
As discussed in the last call, submissions from sources other than text message should also appear in the message log using a similar structure. This means:

- the date and time of when the message is received will be added to the message log
- the type will identify what type of method was used to receive the message
-the field for mobile number will be left blank, unless there's some kind of identifier that can identify what device sent in the entry
-direction will always be inbound, since there is no outbound message sent when app-based submissions are received
-the 'Text' field will parse the data received into a similar format as text messages are received, such as 'XA1001AA1AB4ACfoo', combining the ID used to submit the entry and the data contained in the submission. [Perhaps format it slightly different, such as 'XA: 1001 AA: 1, AB: 4, AC: foo' ? Also, note that when not using text messages, the identifier for a question might not be the standard AA, AB, AC, etc. and rather could be replaced by words or labels]

Feel free to propose alternative ways of doing this if you have other ideas for how to do this

**Comment by blynchNDI** [comment]
This seems to be working well as per requirements. Is there a reason why the phone number shows up as 00000090? Doesn't seem to be a problem though either way

![Screenshot from 2019-07-23 15-32-24](https://user-images.githubusercontent.com/31080607/61741522-1a860580-ad5f-11e9-9549-f8290bac1af3.png)
