### ISSUE TITLE
explore adding a more intuitive QA criteria builder

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#238]
Aha! Link: https://nditech.aha.io/features/APOLLO-125

**Comment by SarahCooperNDI** [comment]
Cut/pasted in from SoW

"Build an interactive logical check dashboard so that new logical checks can be inputted by the front end user in real time - a QA builder of the nature of the Form Builder. This would mean that there needs to be some way on the front end of the database to manually re-run the logical checks as new checks are inputted so that corresponding records would be flagged (or that the logical checks should automatically re-run after every time a new logical check is saved or modified)"

**Comment by blynchNDI** [comment]
The new QA feature looks great. I'll close this, and @SarahCooperNDI or @RLK-NDI can weigh in and open a new issue if there's any tweaks to it they'd like to see
