### ISSUE TITLE
when editing checklists, collapse sections that are already complete to reduce the amount of scrolling needed to get to sections that need work

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#243]
Aha! Link: https://nditech.aha.io/features/APOLLO-121

**Comment by SarahCooperNDI** [comment]
It is not currently clear what causes a checklist to collapse. We think the default should be that the checklist is fully expanded and it should only collapse when the Location/Master data is complete. At present, you can edit the master data so that it is partial but the checklist will remain collapsed (e.x. Observer 11111 in the Testing event)

**Checklist View When You Click on Observer 11111**

![Collapsed Data - 11111](https://user-images.githubusercontent.com/48285413/59951225-350a4d80-9446-11e9-85b6-88b98ece77ca.png)

**Status of Master Data for Observer 11111 When You Expand the Midday Message**

![Expanded Data - 11111](https://user-images.githubusercontent.com/48285413/59951342-a34f1000-9446-11e9-92bb-df804dc73513.png)

**Comment by SarahCooperNDI** [comment]
The green check box to show a complete message is great -- could we also introduce the yellow caution sign for a partial message and the red X for a missing message so that the icons used track with what is on the checklist summary page?

![Caution Sign on Collapsed Checklist](https://user-images.githubusercontent.com/48285413/59951574-5fa8d600-9447-11e9-9020-37b2092f9eb6.png)

**Comment by SarahCooperNDI** [comment]
The checklist dashboard also does not seem to be performing as expected based on the Master/Location data.  Observer 11111 is shown as having three complete messages. But the Master/Location data under Midday is partial.

**Dashboard Shows All Complete Messages**

![Dashboard Not Performing As Expected - Obs 11111](https://user-images.githubusercontent.com/48285413/59952203-591b5e00-9449-11e9-83ef-723bcda0703d.png)

**But Midday Master/Location Data Is Partial**

![Expanded Data - 11111](https://user-images.githubusercontent.com/48285413/59952257-836d1b80-9449-11e9-9e40-ccad08895b11.png)

**Comment by dodumosu** [comment]
@SarahCooperNDI about the list view showing the data to be complete while the location/master data is partial…the list view's source of truth is the individual observer checklists, not the location/master checklists. If this isn't how it's supposed to work, please give some advice on the recommended way to deal with this.

**Comment by takinbo** [comment]
The sections are collapsed when data is (and only is) complete. The green check mark gives context as to why the section is collapsed. I don't think it would add value to add icons for partial and missing statuses for the text sections.

The only time a section is collapsed is when it is complete so the green check mark appears when it is collapsed (please let us know if this is not the case).

As it stands, this only reflects the status of the observer's report and not the location. We could change this behaviour if it makes more sense.

**Comment by SarahCooperNDI** [comment]
@takinbo @dodumosu @blynchNDI Per today's call we should move forward with making the checklists collapse based on the status of the Master/Location data (since otherwise we will run into problems with the multiple observer model) and we should remove the green checklist icon. Many thanks!

**Comment by blynchNDI** [comment]
@SarahCooperNDI and @sarahmoulton can comment, but looks good to me - will close tomorrow unless there are any objections

![Screenshot from 2019-07-16 15-18-48](https://user-images.githubusercontent.com/31080607/61323078-1f860a80-a7dd-11e9-871e-3827499bedcb.png)

**Comment by takinbo** [comment]
Why was this reopened?

**Comment by blynchNDI** [comment]
This was closed by accident before I was able to review - just reopening it for while I review it

**Comment by takinbo** [comment]
:+1:

**Comment by blynchNDI** [comment]
Collapses properly when a checklist is complete
(this means that for multiple observers, when data conflict is turned on, the box only collapses when the master/location value is filled in. When data conflict is turned off, it collapses for each observer individually)
