### ISSUE TITLE
Dashboard breakdown pie charts not appearing

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#506]
On the QA site for the event named Test Event, going to the dashboard for any form and clicking on the pie chart for a breakdown at a lower location level leads to a blank screen. This error seems difficult to replicate - it seems like it may involve unchecking the "display on dashboard" option a administrative division level, but I haven't found a consistent set of steps for reproducing it, and messing around with the 'display on dashboard' settings for various administrative levels often seems to make the issue disappear. My guess is that the application is attempting to send the user to a administrative division breakdown page that is no longer selected for 'display on dashboard' - thus the page is blank, with no hyperlinks to navigate to the further admin division breakdown levels that are designated for 'display on dashboard'.

**Comment by takinbo** [comment]
The possible reason why it's difficult to replicate might have something to do with the bug involving the order of the administrative divisions which was fixed. I was able to see the issue but after re-saving the administrative divisions (which would reset the order), I was unable to observe it again. I would close this issue as it is unlikely that you would be able to observe it on another system that has admin divisions created before the bug was fixed.
